import {
  User,
  Project,
  Milestone,
  FinancialRecord,
  Issue,
  Alert,
  Anomaly,
  AuditLogItem,
  NotificationItem,
  SystemSettings,
  MLExplainResponse,
  MonthlyTrendItem,
  MinistryStat,
  SectorStat
} from '../types';

export const DEMO_USERS: Record<string, { user: User; token: string }> = {
  'admin@pragati.demo': {
    token: 'demo-jwt-token-super-admin-pmo',
    user: {
      id: 1,
      email: 'admin@pragati.demo',
      fullName: 'Shri Rajesh Verma, IAS',
      designation: 'Chief Project Monitoring Officer',
      ministry: 'Cabinet Secretariat',
      department: 'PMO Project Monitoring Group',
      roles: ['ROLE_SUPER_ADMIN', 'ROLE_MINISTRY_ADMIN', 'ROLE_PROJECT_MANAGER', 'ROLE_VIEWER']
    }
  },
  'ministry@pragati.demo': {
    token: 'demo-jwt-token-ministry-admin-morth',
    user: {
      id: 2,
      email: 'ministry@pragati.demo',
      fullName: 'Dr. Sunita Deshmukh',
      designation: 'Joint Secretary (Infrastructure)',
      ministry: 'Ministry of Road Transport and Highways',
      department: 'Highway Development Wing',
      roles: ['ROLE_MINISTRY_ADMIN', 'ROLE_PROJECT_MANAGER', 'ROLE_VIEWER']
    }
  },
  'manager@pragati.demo': {
    token: 'demo-jwt-token-project-manager-nhai',
    user: {
      id: 3,
      email: 'manager@pragati.demo',
      fullName: 'Vikramaditya Rao',
      designation: 'Chief General Manager & Project Director',
      ministry: 'Ministry of Road Transport and Highways',
      department: 'National Highways Authority of India (NHAI)',
      roles: ['ROLE_PROJECT_MANAGER', 'ROLE_VIEWER']
    }
  },
  'field@pragati.demo': {
    token: 'demo-jwt-token-field-officer',
    user: {
      id: 4,
      email: 'field@pragati.demo',
      fullName: 'Ananya Sharma',
      designation: 'Senior Resident Field Engineer',
      ministry: 'Ministry of Jal Shakti',
      department: 'Field Operations Directorate MP',
      roles: ['ROLE_FIELD_OFFICER', 'ROLE_VIEWER']
    }
  },
  'auditor@pragati.demo': {
    token: 'demo-jwt-token-cag-auditor',
    user: {
      id: 5,
      email: 'auditor@pragati.demo',
      fullName: 'K. S. Narayanan',
      designation: 'Principal Director of Audit',
      ministry: 'Comptroller and Auditor General of India',
      department: 'Infrastructure Audit Cell',
      roles: ['ROLE_AUDITOR', 'ROLE_VIEWER']
    }
  },
  'viewer@pragati.demo': {
    token: 'demo-jwt-token-public-viewer',
    user: {
      id: 6,
      email: 'viewer@pragati.demo',
      fullName: 'Public Observer / Stakeholder',
      designation: 'Project Evaluation Analyst',
      ministry: 'NITI Aayog',
      department: 'Development Monitoring Division',
      roles: ['ROLE_VIEWER']
    }
  }
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 1,
    projectCode: 'PRG-HWY-2023-001',
    projectName: 'Atal Tunnel Rohtang Highway Link',
    ministry: 'Ministry of Road Transport and Highways',
    sector: 'Highways',
    state: 'Himachal Pradesh',
    district: 'Kullu',
    location: 'Rohtang Pass Km 10',
    latitude: 32.3667,
    longitude: 77.1744,
    startDate: '2020-01-15',
    plannedEndDate: '2024-03-31',
    projectBudget: 3200.0,
    approvedCost: 3200.0,
    plannedCost: 3200.0,
    actualCost: 3140.0,
    earnedValue: 3200.0,
    physicalProgress: 100.0,
    plannedProgress: 100.0,
    financialProgress: 98.1,
    spi: 1.00,
    cpi: 1.02,
    scheduleVariance: 0,
    costVariance: 60.0,
    currentStatus: 'COMPLETED',
    priority: 'HIGH',
    riskLevel: 'LOW',
    healthScore: 98,
    aiRiskProbability: 0.05,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Project successfully completed and operational. All milestones achieved within approved parameters.',
    createdAt: '2023-01-10T10:00:00Z',
    lastUpdated: '2024-04-01T12:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 2,
    projectCode: 'PRG-RLY-2023-001',
    projectName: 'Chenab River Mega Rail Bridge Section',
    ministry: 'Ministry of Railways',
    sector: 'Railways',
    state: 'Jammu and Kashmir',
    district: 'Reasi',
    location: 'Bakkal-Kauri Rail Span',
    latitude: 33.1539,
    longitude: 74.8817,
    startDate: '2021-02-01',
    plannedEndDate: '2024-08-30',
    projectBudget: 1480.0,
    approvedCost: 1480.0,
    plannedCost: 1480.0,
    actualCost: 1460.0,
    earnedValue: 1480.0,
    physicalProgress: 100.0,
    plannedProgress: 100.0,
    financialProgress: 98.6,
    spi: 1.00,
    cpi: 1.01,
    scheduleVariance: 0,
    costVariance: 20.0,
    currentStatus: 'COMPLETED',
    priority: 'CRITICAL',
    riskLevel: 'LOW',
    healthScore: 97,
    aiRiskProbability: 0.08,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Arch erection, structural health monitoring and trial train runs successfully commissioned.',
    createdAt: '2023-02-15T11:00:00Z',
    lastUpdated: '2024-08-31T09:30:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 3,
    projectCode: 'PRG-PWR-2023-001',
    projectName: 'Bhadla Solar Park Grid Interconnection',
    ministry: 'Ministry of New and Renewable Energy',
    sector: 'Power',
    state: 'Rajasthan',
    district: 'Jodhpur',
    location: 'Bhadla Phase-IV Complex',
    latitude: 27.5383,
    longitude: 71.9167,
    startDate: '2022-03-01',
    plannedEndDate: '2024-06-30',
    projectBudget: 2100.0,
    approvedCost: 2100.0,
    plannedCost: 2100.0,
    actualCost: 2050.0,
    earnedValue: 2100.0,
    physicalProgress: 100.0,
    plannedProgress: 100.0,
    financialProgress: 97.6,
    spi: 1.00,
    cpi: 1.02,
    scheduleVariance: 0,
    costVariance: 50.0,
    currentStatus: 'COMPLETED',
    priority: 'MEDIUM',
    riskLevel: 'LOW',
    healthScore: 99,
    aiRiskProbability: 0.04,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Full 2245 MW solar generation capacity synchronized with the national grid.',
    createdAt: '2023-03-01T08:00:00Z',
    lastUpdated: '2024-07-05T14:20:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 4,
    projectCode: 'PRG-URB-2023-001',
    projectName: 'Surat Diamond Bourse Smart Access Corridor',
    ministry: 'Ministry of Housing and Urban Affairs',
    sector: 'Urban Development',
    state: 'Gujarat',
    district: 'Surat',
    location: 'DREAM City Zone',
    latitude: 21.1167,
    longitude: 72.8000,
    startDate: '2022-06-01',
    plannedEndDate: '2024-05-15',
    projectBudget: 850.0,
    approvedCost: 850.0,
    plannedCost: 850.0,
    actualCost: 835.0,
    earnedValue: 850.0,
    physicalProgress: 100.0,
    plannedProgress: 100.0,
    financialProgress: 98.2,
    spi: 1.00,
    cpi: 1.02,
    scheduleVariance: 0,
    costVariance: 15.0,
    currentStatus: 'COMPLETED',
    priority: 'MEDIUM',
    riskLevel: 'LOW',
    healthScore: 100,
    aiRiskProbability: 0.02,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Multi-modal rapid access transit, flyover, and smart utility network commissioned on schedule.',
    createdAt: '2023-06-10T10:00:00Z',
    lastUpdated: '2024-05-20T16:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 5,
    projectCode: 'PRG-HWY-2024-001',
    projectName: 'Delhi-Mumbai Expressway Spur Link MP',
    ministry: 'Ministry of Road Transport and Highways',
    sector: 'Highways',
    state: 'Madhya Pradesh',
    district: 'Ratlam',
    location: 'Ratlam Bypass Km 42',
    latitude: 23.3315,
    longitude: 75.0367,
    startDate: '2023-01-10',
    plannedEndDate: '2026-03-31',
    projectBudget: 1450.0,
    approvedCost: 1450.0,
    plannedCost: 1087.5,
    actualCost: 1080.0,
    earnedValue: 1131.0,
    physicalProgress: 78.0,
    plannedProgress: 75.0,
    financialProgress: 74.5,
    spi: 1.04,
    cpi: 1.05,
    scheduleVariance: 43.5,
    costVariance: 51.0,
    currentStatus: 'IN_PROGRESS',
    priority: 'HIGH',
    riskLevel: 'LOW',
    healthScore: 95,
    aiRiskProbability: 0.12,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'SPI (1.04) and CPI (1.05) exceed baseline with zero overdue milestones.',
    createdAt: '2023-01-10T09:00:00Z',
    lastUpdated: '2024-10-15T11:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 6,
    projectCode: 'PRG-RLY-2024-001',
    projectName: 'Western Dedicated Freight Corridor Ring',
    ministry: 'Ministry of Railways',
    sector: 'Railways',
    state: 'Rajasthan',
    district: 'Jaipur',
    location: 'Phulera Junction',
    latitude: 26.8756,
    longitude: 75.2415,
    startDate: '2022-09-01',
    plannedEndDate: '2025-12-31',
    projectBudget: 2800.0,
    approvedCost: 2800.0,
    plannedCost: 2296.0,
    actualCost: 2300.0,
    earnedValue: 2352.0,
    physicalProgress: 84.0,
    plannedProgress: 82.0,
    financialProgress: 82.1,
    spi: 1.02,
    cpi: 1.02,
    scheduleVariance: 56.0,
    costVariance: 52.0,
    currentStatus: 'IN_PROGRESS',
    priority: 'HIGH',
    riskLevel: 'LOW',
    healthScore: 92,
    aiRiskProbability: 0.15,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Track electrification & signaling ahead of master schedule.',
    createdAt: '2022-09-01T10:00:00Z',
    lastUpdated: '2024-11-01T14:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 7,
    projectCode: 'PRG-PWR-2024-001',
    projectName: 'Khavda Ultra Mega Solar Park Phase-I',
    ministry: 'Ministry of New and Renewable Energy',
    sector: 'Power',
    state: 'Gujarat',
    district: 'Kutch',
    location: 'Khavda Renewable Zone',
    latitude: 23.8542,
    longitude: 69.7214,
    startDate: '2023-04-01',
    plannedEndDate: '2025-06-30',
    projectBudget: 3200.0,
    approvedCost: 3200.0,
    plannedCost: 2880.0,
    actualCost: 2850.0,
    earnedValue: 2912.0,
    physicalProgress: 91.0,
    plannedProgress: 90.0,
    financialProgress: 89.1,
    spi: 1.01,
    cpi: 1.02,
    scheduleVariance: 32.0,
    costVariance: 62.0,
    currentStatus: 'IN_PROGRESS',
    priority: 'CRITICAL',
    riskLevel: 'LOW',
    healthScore: 96,
    aiRiskProbability: 0.10,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Grid synchronization completed with optimal budget variance.',
    createdAt: '2023-04-01T08:00:00Z',
    lastUpdated: '2024-11-10T10:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 8,
    projectCode: 'PRG-WTR-2024-001',
    projectName: 'Jal Jeevan Multi-Village Piped Supply UP',
    ministry: 'Ministry of Jal Shakti',
    sector: 'Water Supply',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    location: 'Sevapuri Block',
    latitude: 25.3176,
    longitude: 82.9739,
    startDate: '2023-05-15',
    plannedEndDate: '2025-10-31',
    projectBudget: 850.0,
    approvedCost: 850.0,
    plannedCost: 561.0,
    actualCost: 560.0,
    earnedValue: 578.0,
    physicalProgress: 68.0,
    plannedProgress: 66.0,
    financialProgress: 65.8,
    spi: 1.03,
    cpi: 1.03,
    scheduleVariance: 17.0,
    costVariance: 18.0,
    currentStatus: 'IN_PROGRESS',
    priority: 'MEDIUM',
    riskLevel: 'LOW',
    healthScore: 90,
    aiRiskProbability: 0.18,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Household tap connections progressing smoothly across 140 villages.',
    createdAt: '2023-05-15T09:00:00Z',
    lastUpdated: '2024-10-28T16:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 9,
    projectCode: 'PRG-DGT-2024-001',
    projectName: 'BharatNet Gram Panchayat Optical Fiber',
    ministry: 'Ministry of Communications',
    sector: 'Digital Infrastructure',
    state: 'Karnataka',
    district: 'Mysuru',
    location: 'Hunsur Taluk',
    latitude: 12.3072,
    longitude: 76.2921,
    startDate: '2023-02-01',
    plannedEndDate: '2025-08-31',
    projectBudget: 620.0,
    approvedCost: 620.0,
    plannedCost: 434.0,
    actualCost: 430.0,
    earnedValue: 446.4,
    physicalProgress: 72.0,
    plannedProgress: 70.0,
    financialProgress: 69.3,
    spi: 1.03,
    cpi: 1.04,
    scheduleVariance: 12.4,
    costVariance: 16.4,
    currentStatus: 'IN_PROGRESS',
    priority: 'LOW',
    riskLevel: 'LOW',
    healthScore: 93,
    aiRiskProbability: 0.14,
    aiPredictedDelayDays: 0,
    aiExplanationSummary: 'Underground duct laying and GP terminal testing completed.',
    createdAt: '2023-02-01T11:00:00Z',
    lastUpdated: '2024-11-05T12:00:00Z',
    openIssuesCount: 0,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 0,
    activeAlertsCount: 0
  },
  {
    id: 10,
    projectCode: 'PRG-HWY-2024-002',
    projectName: 'Varanasi-Kolkata Economic Corridor Package-3',
    ministry: 'Ministry of Road Transport and Highways',
    sector: 'Highways',
    state: 'Bihar',
    district: 'Gaya',
    location: 'Dobhi Highway Stretch',
    latitude: 24.5833,
    longitude: 84.9500,
    startDate: '2023-03-01',
    plannedEndDate: '2026-06-30',
    projectBudget: 1850.0,
    approvedCost: 1850.0,
    plannedCost: 1110.0,
    actualCost: 1060.0,
    earnedValue: 999.0,
    physicalProgress: 54.0,
    plannedProgress: 60.0,
    financialProgress: 57.3,
    spi: 0.90,
    cpi: 0.94,
    scheduleVariance: -111.0,
    costVariance: -61.0,
    currentStatus: 'DELAYED',
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    healthScore: 74,
    aiRiskProbability: 0.42,
    aiPredictedDelayDays: 18,
    aiExplanationSummary: 'Moderate schedule lag due to monsoon quarrying restrictions in Bihar.',
    createdAt: '2023-03-01T10:00:00Z',
    lastUpdated: '2024-11-12T09:00:00Z',
    openIssuesCount: 1,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 1,
    activeAlertsCount: 1
  },
  {
    id: 11,
    projectCode: 'PRG-HLT-2024-001',
    projectName: 'AIIMS Guwahati Super Specialty Complex',
    ministry: 'Ministry of Health and Family Welfare',
    sector: 'Healthcare',
    state: 'Assam',
    district: 'Kamrup',
    location: 'Changsari Medical Hub',
    latitude: 26.2625,
    longitude: 91.6881,
    startDate: '2022-11-01',
    plannedEndDate: '2025-09-30',
    projectBudget: 1120.0,
    approvedCost: 1120.0,
    plannedCost: 593.6,
    actualCost: 570.0,
    earnedValue: 537.6,
    physicalProgress: 48.0,
    plannedProgress: 53.0,
    financialProgress: 50.9,
    spi: 0.91,
    cpi: 0.94,
    scheduleVariance: -56.0,
    costVariance: -32.4,
    currentStatus: 'DELAYED',
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    healthScore: 72,
    aiRiskProbability: 0.45,
    aiPredictedDelayDays: 22,
    aiExplanationSummary: 'HVAC & specialized medical gas pipeline procurement awaiting vendor sign-off.',
    createdAt: '2022-11-01T09:00:00Z',
    lastUpdated: '2024-11-14T11:30:00Z',
    openIssuesCount: 1,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 1,
    activeAlertsCount: 1
  },
  {
    id: 12,
    projectCode: 'PRG-URB-2024-001',
    projectName: 'Smart City Mobility Hub Pune',
    ministry: 'Ministry of Housing and Urban Affairs',
    sector: 'Urban Development',
    state: 'Maharashtra',
    district: 'Pune',
    location: 'Shivajinagar Intermodal',
    latitude: 18.5204,
    longitude: 73.8567,
    startDate: '2023-01-15',
    plannedEndDate: '2025-11-30',
    projectBudget: 940.0,
    approvedCost: 940.0,
    plannedCost: 639.2,
    actualCost: 620.0,
    earnedValue: 573.4,
    physicalProgress: 61.0,
    plannedProgress: 68.0,
    financialProgress: 66.0,
    spi: 0.90,
    cpi: 0.92,
    scheduleVariance: -65.8,
    costVariance: -46.6,
    currentStatus: 'DELAYED',
    priority: 'MEDIUM',
    riskLevel: 'MEDIUM',
    healthScore: 70,
    aiRiskProbability: 0.48,
    aiPredictedDelayDays: 25,
    aiExplanationSummary: 'Underground utility shifting causing traffic diversion bottlenecks.',
    createdAt: '2023-01-15T14:00:00Z',
    lastUpdated: '2024-11-16T15:00:00Z',
    openIssuesCount: 1,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 1,
    activeAlertsCount: 1
  },
  {
    id: 13,
    projectCode: 'PRG-PRT-2024-001',
    projectName: 'Sagarmala Paradip Port Deep Draft Coal Berth',
    ministry: 'Ministry of Ports, Shipping and Waterways',
    sector: 'Ports & Shipping',
    state: 'Odisha',
    district: 'Jagatsinghpur',
    location: 'Paradip Port South Basin',
    latitude: 20.2644,
    longitude: 86.6744,
    startDate: '2023-06-01',
    plannedEndDate: '2026-03-31',
    projectBudget: 1650.0,
    approvedCost: 1650.0,
    plannedCost: 775.5,
    actualCost: 750.0,
    earnedValue: 693.0,
    physicalProgress: 42.0,
    plannedProgress: 47.0,
    financialProgress: 45.4,
    spi: 0.89,
    cpi: 0.92,
    scheduleVariance: -82.5,
    costVariance: -57.0,
    currentStatus: 'DELAYED',
    priority: 'MEDIUM',
    riskLevel: 'MEDIUM',
    healthScore: 68,
    aiRiskProbability: 0.50,
    aiPredictedDelayDays: 28,
    aiExplanationSummary: 'Coastal regulatory clearance for dredging disposal area under re-assessment.',
    createdAt: '2023-06-01T08:30:00Z',
    lastUpdated: '2024-11-18T10:00:00Z',
    openIssuesCount: 1,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 1,
    activeAlertsCount: 1
  },
  {
    id: 14,
    projectCode: 'PRG-RLY-2024-002',
    projectName: 'Bengaluru Suburban Railway Corridor-2',
    ministry: 'Ministry of Railways',
    sector: 'Railways',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    location: 'Baiyappanahalli-Chikkabanavara',
    latitude: 12.9716,
    longitude: 77.5946,
    startDate: '2023-03-15',
    plannedEndDate: '2026-12-31',
    projectBudget: 2400.0,
    approvedCost: 2400.0,
    plannedCost: 960.0,
    actualCost: 910.0,
    earnedValue: 840.0,
    physicalProgress: 35.0,
    plannedProgress: 40.0,
    financialProgress: 37.9,
    spi: 0.88,
    cpi: 0.92,
    scheduleVariance: -120.0,
    costVariance: -70.0,
    currentStatus: 'DELAYED',
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    healthScore: 66,
    aiRiskProbability: 0.53,
    aiPredictedDelayDays: 32,
    aiExplanationSummary: 'Defense land transfer negotiations at Hebbal section in final approval stage.',
    createdAt: '2023-03-15T12:00:00Z',
    lastUpdated: '2024-11-20T13:45:00Z',
    openIssuesCount: 1,
    criticalIssuesCount: 0,
    overdueMilestonesCount: 1,
    activeAlertsCount: 1
  },
  {
    id: 15,
    projectCode: 'PRG-HWY-2024-003',
    projectName: 'Char Dham All-Weather Highway Pauri Stretch',
    ministry: 'Ministry of Road Transport and Highways',
    sector: 'Highways',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    location: 'Srinagar-Rudraprayag Km 85',
    latitude: 30.2227,
    longitude: 78.7839,
    startDate: '2022-08-01',
    plannedEndDate: '2025-10-31',
    projectBudget: 2100.0,
    approvedCost: 2100.0,
    plannedCost: 1365.0,
    actualCost: 1420.0,
    earnedValue: 1113.0,
    physicalProgress: 53.0,
    plannedProgress: 65.0,
    financialProgress: 67.6,
    spi: 0.82,
    cpi: 0.78,
    scheduleVariance: -252.0,
    costVariance: -307.0,
    currentStatus: 'DELAYED',
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    healthScore: 52,
    aiRiskProbability: 0.76,
    aiPredictedDelayDays: 45,
    aiExplanationSummary: 'Frequent monsoon slope failures and geotechnical stabilization works causing serious delays.',
    createdAt: '2022-08-01T10:00:00Z',
    lastUpdated: '2024-11-21T09:15:00Z',
    openIssuesCount: 2,
    criticalIssuesCount: 1,
    overdueMilestonesCount: 2,
    activeAlertsCount: 2
  },
  {
    id: 16,
    projectCode: 'PRG-PWR-2024-002',
    projectName: 'Subansiri Lower Hydroelectric Project Unit-3',
    ministry: 'Ministry of Power',
    sector: 'Power',
    state: 'Arunachal Pradesh',
    district: 'Lower Subansiri',
    location: 'Gerukamukh Dam Site',
    latitude: 27.5517,
    longitude: 94.2612,
    startDate: '2021-01-10',
    plannedEndDate: '2025-12-31',
    projectBudget: 4200.0,
    approvedCost: 4200.0,
    plannedCost: 3150.0,
    actualCost: 3400.0,
    earnedValue: 2604.0,
    physicalProgress: 62.0,
    plannedProgress: 75.0,
    financialProgress: 80.9,
    spi: 0.83,
    cpi: 0.77,
    scheduleVariance: -546.0,
    costVariance: -796.0,
    currentStatus: 'DELAYED',
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    healthScore: 49,
    aiRiskProbability: 0.80,
    aiPredictedDelayDays: 52,
    aiExplanationSummary: 'Turbine runner delivery delayed; tailrace tunnel excavation slowed by geological faults.',
    createdAt: '2021-01-10T11:00:00Z',
    lastUpdated: '2024-11-22T14:00:00Z',
    openIssuesCount: 2,
    criticalIssuesCount: 1,
    overdueMilestonesCount: 2,
    activeAlertsCount: 2
  },
  {
    id: 17,
    projectCode: 'PRG-URB-2024-002',
    projectName: 'Patna Metro Rail Corridor-1 Underground Stretch',
    ministry: 'Ministry of Housing and Urban Affairs',
    sector: 'Urban Development',
    state: 'Bihar',
    district: 'Patna',
    location: 'Danapur-Mithapur Line',
    latitude: 25.5941,
    longitude: 85.1376,
    startDate: '2023-01-01',
    plannedEndDate: '2027-03-31',
    projectBudget: 3100.0,
    approvedCost: 3100.0,
    plannedCost: 1178.0,
    actualCost: 1280.0,
    earnedValue: 961.0,
    physicalProgress: 31.0,
    plannedProgress: 38.0,
    financialProgress: 41.3,
    spi: 0.82,
    cpi: 0.75,
    scheduleVariance: -217.0,
    costVariance: -319.0,
    currentStatus: 'DELAYED',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    healthScore: 47,
    aiRiskProbability: 0.79,
    aiPredictedDelayDays: 48,
    aiExplanationSummary: 'Tunnel Boring Machine (TBM) deployment halted due to heavy silt strata and water ingress.',
    createdAt: '2023-01-01T10:00:00Z',
    lastUpdated: '2024-11-23T11:00:00Z',
    openIssuesCount: 2,
    criticalIssuesCount: 1,
    overdueMilestonesCount: 2,
    activeAlertsCount: 2
  },
  {
    id: 18,
    projectCode: 'PRG-WTR-2024-002',
    projectName: 'Polavaram Irrigation Left Main Canal Section',
    ministry: 'Ministry of Jal Shakti',
    sector: 'Water Supply',
    state: 'Andhra Pradesh',
    district: 'Eluru',
    location: 'Polavaram Left Bank Km 45',
    latitude: 17.2500,
    longitude: 81.6500,
    startDate: '2022-04-01',
    plannedEndDate: '2026-06-30',
    projectBudget: 2900.0,
    approvedCost: 2900.0,
    plannedCost: 1682.0,
    actualCost: 1810.0,
    earnedValue: 1334.0,
    physicalProgress: 46.0,
    plannedProgress: 58.0,
    financialProgress: 62.4,
    spi: 0.79,
    cpi: 0.74,
    scheduleVariance: -348.0,
    costVariance: -476.0,
    currentStatus: 'DELAYED',
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    healthScore: 44,
    aiRiskProbability: 0.84,
    aiPredictedDelayDays: 58,
    aiExplanationSummary: 'Diaphragm wall redesign and sand-filling stabilization underway post-flood damage.',
    createdAt: '2022-04-01T09:00:00Z',
    lastUpdated: '2024-11-24T16:20:00Z',
    openIssuesCount: 2,
    criticalIssuesCount: 1,
    overdueMilestonesCount: 2,
    activeAlertsCount: 2
  },
  {
    id: 19,
    projectCode: 'PRG-HWY-2024-004',
    projectName: 'Srinagar-Baramulla-Uri 4-Lane Highway Expansion',
    ministry: 'Ministry of Road Transport and Highways',
    sector: 'Highways',
    state: 'Jammu and Kashmir',
    district: 'Baramulla',
    location: 'Pattan-Baramulla Sector',
    latitude: 34.2097,
    longitude: 74.3436,
    startDate: '2022-10-01',
    plannedEndDate: '2025-11-30',
    projectBudget: 1750.0,
    approvedCost: 1750.0,
    plannedCost: 1085.0,
    actualCost: 1190.0,
    earnedValue: 857.5,
    physicalProgress: 49.0,
    plannedProgress: 62.0,
    financialProgress: 68.0,
    spi: 0.79,
    cpi: 0.72,
    scheduleVariance: -227.5,
    costVariance: -332.5,
    currentStatus: 'DELAYED',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    healthScore: 42,
    aiRiskProbability: 0.82,
    aiPredictedDelayDays: 60,
    aiExplanationSummary: 'Severe utility relocation backlog and right-of-way litigation at Sangrama junction.',
    createdAt: '2022-10-01T08:00:00Z',
    lastUpdated: '2024-11-25T10:30:00Z',
    openIssuesCount: 2,
    criticalIssuesCount: 1,
    overdueMilestonesCount: 2,
    activeAlertsCount: 2
  },
  {
    id: 20,
    projectCode: 'PRG-RLY-2024-003',
    projectName: 'Rishikesh-Karanprayag Rail Link Tunnel T-8',
    ministry: 'Ministry of Railways',
    sector: 'Railways',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    location: 'Gholtir Tunnel Portal',
    latitude: 30.2858,
    longitude: 78.9811,
    startDate: '2021-06-01',
    plannedEndDate: '2026-03-31',
    projectBudget: 3800.0,
    approvedCost: 3800.0,
    plannedCost: 2546.0,
    actualCost: 2950.0,
    earnedValue: 1824.0,
    physicalProgress: 48.0,
    plannedProgress: 67.0,
    financialProgress: 77.6,
    spi: 0.72,
    cpi: 0.62,
    scheduleVariance: -722.0,
    costVariance: -1126.0,
    currentStatus: 'DELAYED',
    priority: 'CRITICAL',
    riskLevel: 'CRITICAL',
    healthScore: 28,
    aiRiskProbability: 0.94,
    aiPredictedDelayDays: 95,
    aiExplanationSummary: 'High-stress squeezing rock deformation in Tunnel T-8; emergency NATM re-profiling required.',
    createdAt: '2021-06-01T09:00:00Z',
    lastUpdated: '2024-11-26T15:00:00Z',
    openIssuesCount: 3,
    criticalIssuesCount: 2,
    overdueMilestonesCount: 3,
    activeAlertsCount: 3
  }
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 1,
    projectId: 20,
    name: 'Tunnel T-8 Heading & Bench Excavation',
    plannedStartDate: '2023-01-01',
    plannedEndDate: '2024-06-30',
    weightagePercentage: 40,
    plannedProgress: 100,
    actualProgress: 65,
    status: 'DELAYED',
    responsibleOfficer: 'Chief Engineer (RVNL)',
    overdue: true,
    delayDays: 145,
    createdAt: '2023-01-01T00:00:00Z'
  },
  {
    id: 2,
    projectId: 20,
    name: 'Primary Rock Support & Shotcreting',
    plannedStartDate: '2023-07-01',
    plannedEndDate: '2024-12-31',
    weightagePercentage: 30,
    plannedProgress: 90,
    actualProgress: 45,
    status: 'DELAYED',
    responsibleOfficer: 'Deputy Chief Engineer (Geotech)',
    overdue: true,
    delayDays: 90,
    createdAt: '2023-01-01T00:00:00Z'
  },
  {
    id: 3,
    projectId: 20,
    name: 'Final Concrete Lining & Drainage',
    plannedStartDate: '2025-01-01',
    plannedEndDate: '2026-03-31',
    weightagePercentage: 30,
    plannedProgress: 0,
    actualProgress: 0,
    status: 'NOT_STARTED',
    responsibleOfficer: 'Structural In-charge',
    overdue: false,
    delayDays: 0,
    createdAt: '2023-01-01T00:00:00Z'
  },
  {
    id: 4,
    projectId: 5,
    name: 'Earthwork & Embankment Subgrade',
    plannedStartDate: '2023-02-01',
    plannedEndDate: '2024-02-28',
    weightagePercentage: 35,
    plannedProgress: 100,
    actualProgress: 100,
    status: 'COMPLETED',
    responsibleOfficer: 'Project Director (NHAI)',
    overdue: false,
    createdAt: '2023-01-10T00:00:00Z'
  },
  {
    id: 5,
    projectId: 5,
    name: 'Pavement Quality Concrete (PQC) Laying',
    plannedStartDate: '2024-03-01',
    plannedEndDate: '2025-04-30',
    weightagePercentage: 45,
    plannedProgress: 65,
    actualProgress: 72,
    status: 'IN_PROGRESS',
    responsibleOfficer: 'Quality Assurance Lead',
    overdue: false,
    createdAt: '2023-01-10T00:00:00Z'
  }
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 1,
    projectId: 20,
    projectName: 'Rishikesh-Karanprayag Rail Link Tunnel T-8',
    projectCode: 'PRG-RLY-2024-003',
    ministry: 'Ministry of Railways',
    alertType: 'CRITICAL_DELAY_EVM',
    title: 'Severe SPI & CPI Drift Detected (Critical Risk)',
    severity: 'CRITICAL',
    message: 'Tunnel T-8 Schedule Performance Index dropped to 0.72 with cost overrun variance of ₹1,126 Cr. High squeezing ground conditions.',
    status: 'TRIGGERED',
    escalationLevel: 2,
    createdAt: '2024-11-20T08:30:00Z',
    lastEscalatedAt: '2024-11-25T10:00:00Z'
  },
  {
    id: 2,
    projectId: 15,
    projectName: 'Char Dham All-Weather Highway Pauri Stretch',
    projectCode: 'PRG-HWY-2024-003',
    ministry: 'Ministry of Road Transport and Highways',
    alertType: 'SLOPE_STABILIZATION_FAILURE',
    title: 'Geotechnical Slope Hazard & Milestone Overdue',
    severity: 'HIGH',
    message: 'Slope stabilization milestone overdue by 45 days due to recurrent hill debris near Srinagar Km 85.',
    status: 'TRIGGERED',
    escalationLevel: 1,
    createdAt: '2024-11-22T09:00:00Z',
    lastEscalatedAt: '2024-11-24T12:00:00Z'
  },
  {
    id: 3,
    projectId: 16,
    projectName: 'Subansiri Lower Hydroelectric Project Unit-3',
    projectCode: 'PRG-PWR-2024-002',
    ministry: 'Ministry of Power',
    alertType: 'EQUIPMENT_PROCUREMENT_LAG',
    title: 'Turbine Runner Delivery Delayed (52 Days)',
    severity: 'HIGH',
    message: 'Heavy logistics vendor delay in transporting 180T runner from port to Gerukamukh site.',
    status: 'ACKNOWLEDGED',
    escalationLevel: 1,
    acknowledgedBy: 'Dr. Sunita Deshmukh',
    acknowledgedAt: '2024-11-23T14:30:00Z',
    createdAt: '2024-11-22T11:00:00Z'
  },
  {
    id: 4,
    projectId: 10,
    projectName: 'Varanasi-Kolkata Economic Corridor Package-3',
    projectCode: 'PRG-HWY-2024-002',
    ministry: 'Ministry of Road Transport and Highways',
    alertType: 'MATERIAL_QUARRY_PERMIT',
    title: 'Aggregate Supply Disruption in Gaya Belt',
    severity: 'MEDIUM',
    message: 'Quarrying environmental clearance renewal pending with Bihar State Pollution Control Board.',
    status: 'TRIGGERED',
    escalationLevel: 0,
    createdAt: '2024-11-26T07:15:00Z'
  }
];

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 1,
    projectId: 20,
    projectName: 'Rishikesh-Karanprayag Rail Link Tunnel T-8',
    projectCode: 'PRG-RLY-2024-003',
    ministry: 'Ministry of Railways',
    title: 'High-Stress Rock Convergence at RD 4+200',
    description: 'Squeezing rock deformation exceeding 350mm observed in tunnel arch. Requires high-yield steel ribs and double-layer lattice girders.',
    category: 'TECHNICAL',
    priority: 'CRITICAL',
    severity: 'CRITICAL',
    status: 'IN_PROGRESS',
    assignedTo: 'Vikramaditya Rao',
    assignedToName: 'Chief General Manager (Technical)',
    reportedBy: 'Field Resident Geologist',
    costImpactCr: 85.0,
    scheduleImpactDays: 60,
    createdAt: '2024-11-18T10:00:00Z',
    comments: [
      {
        id: 101,
        authorName: 'Vikramaditya Rao',
        authorRole: 'Chief General Manager & Project Director',
        content: 'Specialized Norwegian tunneling consultant team mobilized for in-situ stress assessment.',
        createdAt: '2024-11-20T14:00:00Z'
      }
    ]
  },
  {
    id: 2,
    projectId: 15,
    projectName: 'Char Dham All-Weather Highway Pauri Stretch',
    projectCode: 'PRG-HWY-2024-003',
    ministry: 'Ministry of Road Transport and Highways',
    title: 'Hill Slope Subsidence near Km 85 Bridge Approach',
    description: 'Continuous debris flow blocking construction access road and threatening pier foundation stability.',
    category: 'ENVIRONMENT',
    priority: 'HIGH',
    severity: 'HIGH',
    status: 'OPEN',
    assignedTo: 'Project Director (NHAI Uttarakhand)',
    reportedBy: 'Resident Engineer',
    costImpactCr: 24.5,
    scheduleImpactDays: 30,
    createdAt: '2024-11-21T08:30:00Z',
    comments: []
  },
  {
    id: 3,
    projectId: 14,
    projectName: 'Bengaluru Suburban Railway Corridor-2',
    projectCode: 'PRG-RLY-2024-002',
    ministry: 'Ministry of Railways',
    title: 'Defense Land Transfer NOC Pending at Hebbal',
    description: '14.2 acres of defense land parcel required for track alignment awaiting final Ministry of Defence sanction.',
    category: 'LAND_ACQUISITION',
    priority: 'HIGH',
    severity: 'HIGH',
    status: 'OPEN',
    assignedTo: 'KRIDE Nodal Officer',
    reportedBy: 'Land Acquisition Cell',
    costImpactCr: 0.0,
    scheduleImpactDays: 45,
    createdAt: '2024-11-15T11:00:00Z',
    comments: []
  }
];

export const INITIAL_FINANCIALS: FinancialRecord[] = [
  {
    id: 1,
    projectId: 20,
    fiscalYear: 'FY 2024-25',
    recordMonth: 'Oct 2024',
    plannedExpenditure: 240.0,
    actualExpenditure: 310.0,
    committedExpenditure: 450.0,
    cumulativeExpenditure: 2950.0,
    costVariance: -70.0,
    cpiAtRecord: 0.62,
    remarks: 'Emergency geological stabilization and heavy grouting material procurement.',
    recordedBy: 'Finance Officer (RVNL)',
    createdAt: '2024-10-31T18:00:00Z'
  },
  {
    id: 2,
    projectId: 5,
    fiscalYear: 'FY 2024-25',
    recordMonth: 'Oct 2024',
    plannedExpenditure: 110.0,
    actualExpenditure: 105.0,
    committedExpenditure: 150.0,
    cumulativeExpenditure: 1080.0,
    costVariance: 5.0,
    cpiAtRecord: 1.05,
    remarks: 'PQC paving payments released on milestone verification.',
    recordedBy: 'Accounts Officer (NHAI MP)',
    createdAt: '2024-10-31T17:30:00Z'
  }
];

export const INITIAL_ANOMALIES: Anomaly[] = [
  {
    id: 1,
    projectId: 20,
    projectName: 'Rishikesh-Karanprayag Rail Link Tunnel T-8',
    projectCode: 'PRG-RLY-2024-003',
    anomalyType: 'EVM_EXTREME_DIVERGENCE',
    description: 'CPI (0.62) diverged from National Benchmark by -38%. Expenditure velocity exceeds physical milestone output by 61%.',
    severity: 'CRITICAL',
    status: 'DETECTED',
    detectedAt: '2024-11-20T08:00:00Z'
  },
  {
    id: 2,
    projectId: 15,
    projectName: 'Char Dham All-Weather Highway Pauri Stretch',
    projectCode: 'PRG-HWY-2024-003',
    anomalyType: 'SCHEDULE_COMPLIANCE_DROP',
    description: 'Physical progress stalled for 3 consecutive fortnights due to slope failures.',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    detectedAt: '2024-11-21T09:00:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 1,
    userEmail: 'admin@pragati.demo',
    userName: 'Shri Rajesh Verma, IAS',
    userRole: 'ROLE_SUPER_ADMIN',
    action: 'ESCALATION_OVERRIDE',
    entityType: 'ALERT',
    entityName: 'Tunnel T-8 Critical EVM Alert',
    entityId: 1,
    oldValue: 'LEVEL_1',
    newValue: 'LEVEL_2',
    details: 'Auto-escalated to Cabinet Secretary Command Center due to 52-day delay threshold breach.',
    timestamp: '2024-11-25T10:00:00Z'
  },
  {
    id: 2,
    userEmail: 'manager@pragati.demo',
    userName: 'Vikramaditya Rao',
    userRole: 'ROLE_PROJECT_MANAGER',
    action: 'PROGRESS_UPDATE',
    entityType: 'PROJECT',
    entityName: 'Delhi-Mumbai Expressway Spur Link MP',
    entityId: 5,
    oldValue: '75.0% Physical',
    newValue: '78.0% Physical',
    details: 'PQC stretch Km 35-42 inspection completed and approved.',
    timestamp: '2024-11-24T14:30:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    recipientUser: 'admin@pragati.demo',
    title: 'Critical Escalation Alert: Rishikesh-Karanprayag T-8',
    message: 'Project PRG-RLY-2024-003 has been escalated to Apex Level 2. SPI is 0.72 with ₹1,126 Cr cost overrun.',
    type: 'ALERT_ESCALATION',
    relatedProjectId: 20,
    severity: 'CRITICAL',
    isRead: false,
    createdAt: '2024-11-25T10:00:00Z'
  },
  {
    id: 2,
    recipientUser: 'admin@pragati.demo',
    title: 'Monthly DPR Progress Report Generated',
    message: 'National Infrastructure Monthly Executive Summary for November 2024 is ready for review.',
    type: 'REPORT_READY',
    severity: 'INFO',
    isRead: false,
    createdAt: '2024-11-26T06:00:00Z'
  }
];

export const INITIAL_SETTINGS: SystemSettings = {
  thresholds: {
    critical_spi: '0.75',
    critical_cpi: '0.75',
    high_spi: '0.85',
    high_cpi: '0.85',
    medium_spi: '0.95',
    medium_cpi: '0.95',
    stale_update_days: '14',
    cost_overrun_pct: '10'
  },
  weights: {
    weight_schedule: 30,
    weight_cost: 25,
    weight_milestone: 20,
    weight_issues: 15,
    weight_regularity: 10
  },
  general: {
    platform_name: 'PRAGATI 2.0 National Dashboard',
    monitoring_body: 'Cabinet Secretariat PMO Wing',
    escalation_l1_mins: '5',
    escalation_l2_mins: '10'
  }
};

export const MOCK_TRENDS: MonthlyTrendItem[] = [
  { month: 'Jun 2024', plannedProgress: 52, actualProgress: 51, plannedSpend: 14200, actualSpend: 14100, spi: 0.98, cpi: 1.01 },
  { month: 'Jul 2024', plannedProgress: 58, actualProgress: 56, plannedSpend: 16800, actualSpend: 16900, spi: 0.96, cpi: 0.99 },
  { month: 'Aug 2024', plannedProgress: 64, actualProgress: 61, plannedSpend: 19400, actualSpend: 19800, spi: 0.95, cpi: 0.98 },
  { month: 'Sep 2024', plannedProgress: 70, actualProgress: 66, plannedSpend: 22100, actualSpend: 22700, spi: 0.94, cpi: 0.97 },
  { month: 'Oct 2024', plannedProgress: 76, actualProgress: 71, plannedSpend: 25000, actualSpend: 25800, spi: 0.93, cpi: 0.97 },
  { month: 'Nov 2024', plannedProgress: 82, actualProgress: 75, plannedSpend: 28200, actualSpend: 29400, spi: 0.91, cpi: 0.96 }
];
