apiVersion: v1
kind: Secret
metadata:
  name: pragati-secrets
  namespace: pragati
  labels:
    app.kubernetes.io/name: pragati
type: Opaque
stringData:
  POSTGRES_USER: "pragati_user"
  POSTGRES_PASSWORD: "pragati_password"
  SPRING_DATASOURCE_USERNAME: "pragati_user"
  SPRING_DATASOURCE_PASSWORD: "pragati_password"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
